<?xml version="1.0" encoding="utf-8"?>
<TestRun id="62871f58-fe7f-4458-94b5-06a517b821a5" name="Usuario@NELTBR43 2025-05-07 12:38:27" runUser="NELTBR43\Usuario" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2025-05-07T12:38:27.7935417-03:00" queuing="2025-05-07T12:38:27.7935424-03:00" start="2025-05-07T12:38:21.6386976-03:00" finish="2025-05-07T12:38:27.8026656-03:00" />
  <TestSettings name="default" id="99f54f3e-5ecb-42a8-8c14-7a2c82267aae">
    <Deployment runDeploymentRoot="Usuario_NELTBR43_2025-05-07_12_38_27" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="b1eb95a1-a65e-44d5-916e-17e4f1eae30d" testId="b37d279b-f000-baf3-eff5-feb93774922b" testName="InvalidLoginAttempt" computerName="NELTBR43" duration="00:00:04.2395530" startTime="2025-05-07T12:38:23.2007804-03:00" endTime="2025-05-07T12:38:27.4402531-03:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="b1eb95a1-a65e-44d5-916e-17e4f1eae30d">
      <Output>
        <StdOut>Given I am on the login page&#xD;
-&gt; done: LoginSteps.GivenIAmOnTheLoginPage() (3,3s)&#xD;
When I enter invalid credentials&#xD;
-&gt; done: LoginSteps.WhenIEnterInvalidCredentials() (0,3s)&#xD;
Then I should see an error message&#xD;
-&gt; done: LoginSteps.ThenIShouldSeeAnErrorMessage() (0,7s)</StdOut>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="InvalidLoginAttempt" storage="c:\users\usuario\documents\code\seleniumtests\bin\debug\net8.0\seleniumtests.dll" id="b37d279b-f000-baf3-eff5-feb93774922b">
      <Execution id="b1eb95a1-a65e-44d5-916e-17e4f1eae30d" />
      <TestMethod codeBase="C:\Users\Usuario\Documents\Code\SeleniumTests\bin\Debug\net8.0\SeleniumTests.dll" adapterTypeName="executor://nunit3testexecutor/" className="SeleniumTests.Features.LoginFeatureFeature" name="InvalidLoginAttempt" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="b37d279b-f000-baf3-eff5-feb93774922b" executionId="b1eb95a1-a65e-44d5-916e-17e4f1eae30d" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Resultados que não estão em uma lista" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="Todos os resultados carregados" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>NUnit Adapter 4.2.0.0: Test execution started&#xD;
Running all tests in C:\Users\Usuario\Documents\Code\SeleniumTests\bin\Debug\net8.0\SeleniumTests.dll&#xD;
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Non-Explicit run&#xD;
Starting ChromeDriver 136.0.7103.49 (031848bc6ad02b97854f3d6154d3aefd0434756a-refs/branch-heads/7103@{#1423}) on port 57880&#xD;
Only local connections are allowed.&#xD;
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.&#xD;
ChromeDriver was started successfully on port 57880.&#xD;
NUnit Adapter 4.2.0.0: Test execution complete&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="NELTBR43" outcome="Warning" timestamp="2025-05-07T12:38:27.4574154-03:00">
        <Text>Given I am on the login page&#xD;
-&gt; done: LoginSteps.GivenIAmOnTheLoginPage() (3,3s)&#xD;
When I enter invalid credentials&#xD;
-&gt; done: LoginSteps.WhenIEnterInvalidCredentials() (0,3s)&#xD;
Then I should see an error message&#xD;
-&gt; done: LoginSteps.ThenIShouldSeeAnErrorMessage() (0,7s)&#xD;
</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>