<?xml version="1.0" encoding="utf-8"?>
<TestRun id="6e77565a-1468-4ebe-b5b2-9fa9096e5a45" name="Usuario@NELTBR43 2025-05-07 13:42:49" runUser="NELTBR43\Usuario" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2025-05-07T13:42:49.5524450-03:00" queuing="2025-05-07T13:42:49.5524454-03:00" start="2025-05-07T13:42:39.5842800-03:00" finish="2025-05-07T13:42:49.5736774-03:00" />
  <TestSettings name="default" id="de476036-c9cf-41bb-b67c-24d0d74aeebe">
    <Deployment runDeploymentRoot="Usuario_NELTBR43_2025-05-07_13_42_49" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="b36f850f-0fbb-4017-a72f-e958334e8cac" testId="b37d279b-f000-baf3-eff5-feb93774922b" testName="InvalidLoginAttempt" computerName="NELTBR43" duration="00:00:07.1972890" startTime="2025-05-07T13:42:42.2341380-03:00" endTime="2025-05-07T13:42:49.4313304-03:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="b36f850f-0fbb-4017-a72f-e958334e8cac">
      <Output>
        <StdOut>Given I am on the login page&#xD;
-&gt; done: LoginSteps.GivenIAmOnTheLoginPage() (5,6s)&#xD;
When I enter invalid credentials&#xD;
-&gt; done: LoginSteps.WhenIEnterInvalidCredentials() (0,9s)&#xD;
Then I should see an error message&#xD;
-&gt; done: LoginSteps.ThenIShouldSeeAnErrorMessage() (0,7s)</StdOut>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="InvalidLoginAttempt" storage="c:\users\usuario\documents\code\seleniumtests\bin\debug\net8.0\seleniumtests.dll" id="b37d279b-f000-baf3-eff5-feb93774922b">
      <Execution id="b36f850f-0fbb-4017-a72f-e958334e8cac" />
      <TestMethod codeBase="C:\Users\Usuario\Documents\Code\SeleniumTests\bin\Debug\net8.0\SeleniumTests.dll" adapterTypeName="executor://nunit3testexecutor/" className="SeleniumTests.Features.LoginFeatureFeature" name="InvalidLoginAttempt" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="b37d279b-f000-baf3-eff5-feb93774922b" executionId="b36f850f-0fbb-4017-a72f-e958334e8cac" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Resultados que não estão em uma lista" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="Todos os resultados carregados" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>NUnit Adapter 4.2.0.0: Test execution started&#xD;
Running all tests in C:\Users\Usuario\Documents\Code\SeleniumTests\bin\Debug\net8.0\SeleniumTests.dll&#xD;
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Non-Explicit run&#xD;
Starting ChromeDriver 136.0.7103.49 (031848bc6ad02b97854f3d6154d3aefd0434756a-refs/branch-heads/7103@{#1423}) on port 58922&#xD;
Only local connections are allowed.&#xD;
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.&#xD;
ChromeDriver was started successfully on port 58922.&#xD;
NUnit Adapter 4.2.0.0: Test execution complete&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="NELTBR43" outcome="Warning" timestamp="2025-05-07T13:42:49.4491236-03:00">
        <Text>Given I am on the login page&#xD;
-&gt; done: LoginSteps.GivenIAmOnTheLoginPage() (5,6s)&#xD;
When I enter invalid credentials&#xD;
-&gt; done: LoginSteps.WhenIEnterInvalidCredentials() (0,9s)&#xD;
Then I should see an error message&#xD;
-&gt; done: LoginSteps.ThenIShouldSeeAnErrorMessage() (0,7s)&#xD;
</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>